const Data = {
    carddata: [
        {
            id: 1,
            pic: "https://images.olx.com.pk/thumbnails/261948246-400x300.webp",
            title: "Apple Iphone 14pro",
            desc: "Rs 129,999",
            location: "Mirpur khas",
        },
        {
            id: 2,
            pic: "https://images.olx.com.pk/thumbnails/289416607-400x300.webp",
            title: "Bike 125cc",
            desc: "Rs 200,000",
            location: "Karachi",
        },
        {
            id: 3,
            pic: "https://images.olx.com.pk/thumbnails/289416607-400x300.webp",
            title: "Dell workstation",
            desc: "Rs 120,000",
            location: "Lahore",
        },
        {
            id: 4,
            pic: "https://images.olx.com.pk/thumbnails/289416607-400x300.webp",
            title: "Treadmill Machine",
            desc: "Rs 135,000",
            location: "Mirpur khas",
        },
        {
            id: 5,
            pic: "https://images.olx.com.pk/thumbnails/289416607-400x300.webp",
            title: "S 20 lite",
            desc: "Rs 15,000",
            location: "Mirpur khas",
        },
        {
            id: 6,
            pic: "https://images.olx.com.pk/thumbnails/289416607-400x300.webp",
            title: "Oval Chopper",
            desc: "Rs 950",
            location: "Mirpur khas",
        },
        {
            id: 7,
            pic: "https://images.olx.com.pk/thumbnails/289416607-400x300.webp",
            title: "Vivo c21e",
            desc: "Rs 43,000",
            location: "Mirpur khas",
        },
        {
            id: 8,
            pic: "https://images.olx.com.pk/thumbnails/289416607-400x300.webp",
            title: "Nikon D3200 lens",
            desc: "Rs 18,500",
            location: "Mirpur khas",
        },
        {
            id: 9,
            pic: "https://images.olx.com.pk/thumbnails/289416607-400x300.webp",
            title: "Ps5",
            desc: "Rs 100,000",
            location: "Mirpur khas",
        },
        {
            id: 10,
            pic: "https://images.olx.com.pk/thumbnails/289416607-400x300.webp",
            title: "Cd playes",
            desc: "Rs 3,000",
            location: "Mirpur khas",
        },
        {
            id: 11,
            pic: "https://images.olx.com.pk/thumbnails/289416607-400x300.webp",
            title: "Hp laptop",
            desc: "Rs 50,000",
            location: "Mirpur khas",
        },
        {
            id: 12,
            pic: "https://images.olx.com.pk/thumbnails/289416607-400x300.webp",
            title: "S21 Ultra",
            desc: "Rs 185,000",
            location: "Mirpur khas",
        },
        {
            id: 13,
            pic: "https://images.olx.com.pk/thumbnails/289416607-400x300.webp",
            title: "Note 10",
            desc: "Rs 30,000",
            location: "Mirpur khas",
        },
        {
            id: 14,
            pic: "https://images.olx.com.pk/thumbnails/289416607-400x300.webp",
            title: "Nikon Camera",
            desc: "Rs 30,000",
            location: "Mirpur khas",
        },

        {
            id: 15,
            pic: "https://images.olx.com.pk/thumbnails/289416607-400x300.webp",
            title: "GTa 5 Online",
            desc: "Rs 2,000",
            location: "Mirpur khas",
        },
        {
            id: 16,
            pic: "https://images.olx.com.pk/thumbnails/289416607-400x300.webp",
            title: "Oval Chopper",
            desc: "Rs 950",
            location: "Mirpur khas",
        },
        {
            id: 17,
            pic: "https://images.olx.com.pk/thumbnails/289416607-400x300.webp",
            title: "Oval Chopper",
            desc: "Rs 950",
            location: "Mirpur khas",
        },
        {
            id: 18,
            pic: "https://images.olx.com.pk/thumbnails/289416607-400x300.webp",
            title: "Oval Chopper",
            desc: "Rs 950",
            location: "Mirpur khas",
        },
        {
            id: 19,
            pic: "https://images.olx.com.pk/thumbnails/289416607-400x300.webp",
            title: "Oval Chopper",
            desc: "Rs 950",
            location: "Mirpur khas",
        },
        {
            id: 20,
            pic: "https://images.olx.com.pk/thumbnails/289416607-400x300.webp",
            title: "Oval Chopper",
            desc: "Rs 950",
            location: "Mirpur khas",
        },
    ]
}
export default Data;